### ISSUE TITLE
Request SourceHanSansCN-ExtraLight + Heavy

### ISSUE THREAD

**Issue by gregbown** [magiclen/source-han-sans-cn-woff2#1]
I found [here](https://github.com/Pal3love/Source-Han-TrueType) where they converted all of the Adobe Source Han Sans fonts to true type.  I was so happy to find your repo with woff2.  Thank you!
I tried to build Googles tool to complete the set but ran into some build issues... so wondering if you would be so kind as to add the extra light and heavy since you have a working process.
Either way thank you again mr Li

**Comment by magiclen** [comment]
Okay. But since I don't use other weights frequently and I want the size of this repository (and others of my repositories related to `source-han-sans-*`) not to be so large, I will create new repositories (maybe named like `source-han-sans-cn-woff2-extra`) to store those woff2 fonts.

**Comment by gregbown** [comment]
@magiclen Very kind of you, thank you!

**Comment by magiclen** [comment]
These repositories have been created.

[magiclen/source-han-sans-tw-woff2-extra](https://github.com/magiclen/source-han-sans-tw-woff2-extra)
[magiclen/source-han-sans-hw-tw-woff2-extra](https://github.com/magiclen/source-han-sans-hw-tw-woff2-extra)
[magiclen/source-han-sans-cn-woff2-extra](https://github.com/magiclen/source-han-sans-cn-woff2-extra)
[magiclen/source-han-sans-hw-cn-woff2-extra](https://github.com/magiclen/source-han-sans-hw-cn-woff2-extra)

[magiclen/source-han-sans-tc-woff2-extra](https://github.com/magiclen/source-han-sans-tc-woff2-extra)
[magiclen/source-han-sans-hw-tc-woff2-extra](https://github.com/magiclen/source-han-sans-hw-tc-woff2-extra)
[magiclen/source-han-sans-sc-woff2-extra](https://github.com/magiclen/source-han-sans-sc-woff2-extra)
[magiclen/source-han-sans-hw-sc-woff2-extra](https://github.com/magiclen/source-han-sans-hw-sc-woff2-extra)
